Repository googleapis/nodejs-logging, pull requests merged in 2018-03, with the labels that each got.

#81 gcp-metadata uses promises.
  src/metadata.js
  test/metadata.js
Labels: cla: yes

#82 1.1.5
  package.json
  samples/package.json
Labels: cla: yes

#83 Extend system test delay.
  system-test/logging.js
Labels: cla: yes

#87 correctly locate gcp-metadata property
  src/metadata.js
  test/metadata.js
Labels: cla: yes

#88 v1.1.7
  package.json
  samples/package.json
Labels: cla: yes

#94 Upgrade repo-tools and regenerate scaffolding.
  .github/ISSUE_TEMPLATE.md
  .gitignore
  CONTRIBUTORS
  README.md
  package-lock.json
  package.json
  samples/README.md
  samples/package-lock.json
  samples/package.json
  src/metadata.js
Labels: cla: yes

#92 fix: Unique-ify getEntries resourceNames
  src/index.js
  test/index.js
Labels: cla: yes

#95 v1.2.0
  package-lock.json
  package.json
  samples/package-lock.json
Labels: cla: yes, status: blocked

#97 chore: setup nighty build in CircleCI
  .circleci/config.yml
  .circleci/get_workflow_name.py
Labels: cla: yes

#98 Update google-auto-auth
  package-lock.json
  package.json
  samples/package-lock.json
Labels: cla: yes

#99 chore: make samples depend on the current version
  samples/package-lock.json
  samples/package.json
Labels: cla: no

#101 chore: workaround for repo-tools EPERM
  .circleci/config.yml
Labels: cla: yes

#103 chore: one more workaround for repo-tools EPERM
  .circleci/config.yml
Labels: cla: yes
