Repository googleapis/nodejs-logging, pull requests merged in 2019-03, with the labels that each got.

#408 refactor (typescript): noImplilcitAny
  package.json
  proto/logging_config.d.ts
  src/index.ts
  src/log.ts
  src/sink.ts
  system-test/logging.ts
  test/index.ts
  test/sink.ts
Labels: cla: yes

#410 chore(deps): update @google-cloud/pubsub to v0.27.0
  package.json
Labels: cla: yes

#411 build: update release configuration
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#413 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#414 fix: do not load duplicate scopes
  src/index.ts
  test/index.ts
Labels: cla: yes

#415 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#409 refactor: clean up types and imports
  .gitignore
  package.json
  samples/.eslintrc.yml
  src/entry.ts
  src/index.ts
  src/log.ts
  src/sink.ts
  system-test/logging.ts
  test/entry.ts
  test/index.ts
  test/middleware/express/test-make-middleware.ts
  test/middleware/test-context.ts
Labels: :rotating_light:, cla: yes

#422 refactor: update json import paths
  src/v2/config_service_v2_client.js
  src/v2/logging_service_v2_client.js
  src/v2/metrics_service_v2_client.js
  synth.metadata
Labels: cla: yes

#424 test: reap deleted resources to avoid collisions
  src/log.ts
  src/metadata.ts
  system-test/logging.ts
Labels: cla: yes, needs work

#428 build: update kokoro release configuration
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#423 Release @google-cloud/logging v4.5.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#430 fix(ts): do not require storage/pubsub types, add install test
  package.json
  src/index.ts
  system-test/fixtures/sample/package.json
  system-test/fixtures/sample/src/index.ts
  system-test/fixtures/sample/tsconfig.json
  system-test/install.ts
Labels: cla: yes

#431 Release @google-cloud/logging v4.5.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#433 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#436 chore: use new GCF env vars in descriptor
  src/metadata.ts
  test/metadata.ts
Labels: cla: yes

#439 fix: include 'x-goog-request-params' header in requests
  src/v2/config_service_v2_client.js
  src/v2/logging_service_v2_client.js
  src/v2/metrics_service_v2_client.js
  synth.metadata
Labels: cla: yes
