Repository googleapis/nodejs-logging, pull requests merged in 2019-07, with the labels that each got.

#529 feat: add path template parsing for billing, organizations, and folders
  src/v2/config_service_v2_client.js
  src/v2/logging_service_v2_client.js
  src/v2/metrics_service_v2_client.js
  synth.metadata
Labels: cla: yes

#530 chore: release 5.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#543 docs: use the jsdoc-fresh theme
  .jsdoc.js
  package.json
Labels: cla: yes, kokoro:force-run

#544 docs: document apiEndpoint over servicePath
  src/v2/config_service_v2_client.js
  src/v2/logging_service_v2_client.js
  src/v2/metrics_service_v2_client.js
Labels: cla: yes
