Repository googleapis/nodejs-logging, pull requests merged in 2019-05, with the labels that each got.

#460 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#461 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#462 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#468 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: automerge, cla: yes

#469 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#470 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#453 refactor: log.ts to async-first
  src/log.ts
  system-test/logging.ts
  test/log.ts
Labels: :rotating_light:, cla: yes

#454 chore(docs): formatting updates
  src/v2/doc/google/protobuf/doc_any.js
  src/v2/doc/google/protobuf/doc_field_mask.js
  src/v2/doc/google/protobuf/doc_timestamp.js
  synth.metadata
Labels: :rotating_light:, cla: yes

#473 fix: DEADLINE_EXCEEDED no longer listed as idempotent
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  src/v2/config_service_v2_client.js
  src/v2/config_service_v2_client_config.json
  src/v2/doc/google/api/doc_monitored_resource.js
  src/v2/logging_service_v2_client_config.json
  src/v2/metrics_service_v2_client.js
  src/v2/metrics_service_v2_client_config.json
  synth.metadata
Labels: cla: yes

#478 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v2/config_service_v2_client_config.json
  src/v2/logging_service_v2_client_config.json
  src/v2/metrics_service_v2_client_config.json
  synth.metadata
Labels: cla: yes

#480 docs: update jsdoc formatting
  src/v2/doc/google/api/doc_metric.js
  src/v2/doc/google/api/doc_monitored_resource.js
  synth.metadata
Labels: cla: yes

#476 use originalUrl for Express middleware's request url
  src/middleware/express/make-http-request.ts
  src/middleware/express/make-middleware.ts
  test/middleware/express/test-make-http-request.ts
Labels: cla: yes

#486 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#487 chore: release 5.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#491 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v2/config_service_v2_client.js
  src/v2/logging_service_v2_client.js
  src/v2/metrics_service_v2_client.js
  synth.metadata
Labels: cla: yes

#492 chore: release 5.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#493 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#494 refactor: drop dependency on pify
  package.json
  src/metadata.ts
Labels: cla: yes

#495 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#498 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#499 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
