Repository googleapis/nodejs-logging, pull requests merged in 2019-04, with the labels that each got.

#445 refactor: use execSync for tests
  package.json
  samples/package.json
  samples/test/.eslintrc.yml
  samples/test/fluent.test.js
  samples/test/logs.test.js
  samples/test/quickstart.test.js
  samples/test/sinks.test.js
  test/metadata.ts
Labels: automerge, cla: yes

#412 refactor: index.ts to async-first
  src/index.ts
  src/log.ts
  system-test/fixtures/sample/src/index.ts
  test/index.ts
  test/log.ts
Labels: :rotating_light:, cla: yes

#452 refactor: sink.ts to async-first
  src/sink.ts
  test/sink.ts
Labels: :rotating_light:, cla: yes

#458 update to .nycrc with --all enabled
  .nycrc
Labels: cla: yes
