Repository googleapis/nodejs-logging, pull requests merged in 2020-09, with the labels that each got.

#887 docs: fix broken links in sample
  samples/logs.js
  samples/sinks.js
Labels: cla: yes

#886 build: delete Blunderbuss
  .github/blunderbuss.yml
Labels: api: logging, automerge, cla: yes

#882 test: fix flaky sample tests
  samples/test/http-request.test.js
  samples/test/logs.test.js
  samples/test/quickstart.test.js
  samples/test/sinks.test.js
Labels: api: logging, cla: yes

#891 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full
