Repository googleapis/nodejs-logging, pull requests merged in 2020-11, with the labels that each got.

#925 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#926 docs: region tag mismatch in http request sample
  samples/http-request.js
Labels: api: logging, cla: yes

#928 chore: add generated files bot to repo
  .github/generated-files-bot.yml
Labels: api: logging, cla: yes, priority: p2, type: process

#930 test: make system tests fail accurately locally
  system-test/logging.ts
Labels: api: logging, cla: yes, priority: p2, type: process

#931 test: deflake and speed up system and sample tests
  samples/test/logs.test.js
  system-test/logging.ts
Labels: api: logging, cla: yes, priority: p2, type: process

#932 chore: add blunderbuss
  .github/blunderbuss.yml
Labels: api: logging, cla: yes, priority: p2

#935 fix: do not modify options object, use defaultScopes
  package.json
  src/v2/config_service_v2_client.ts
  src/v2/logging_service_v2_client.ts
  src/v2/metrics_service_v2_client.ts
  synth.metadata
  system-test/install.ts
Labels: api: logging, automerge, cla: yes

#937 feat: accept entry.timestamp string input in RFC3339 format
  src/entry.ts
  test/entry.ts
Labels: api: logging, cla: yes, priority: p2

#933 docs(sample): improve advanced log sample
  samples/http-request.js
  samples/logs.js
  samples/test/logs.test.js
Labels: api: logging, cla: yes

#948 build: compile-protos before run-compile to fix synthtool failure
  package.json
Labels: api: logging, cla: yes, priority: p1

#950 feat: Makes remaining LogBucket and LogViews methods public
  protos/google/logging/v2/logging_config.proto
  protos/google/logging/v2/logging_metrics.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v2/config_service_v2_client.ts
  src/v2/config_service_v2_client_config.json
  src/v2/logging_service_v2_client.ts
  src/v2/metrics_service_v2_client.ts
  synth.metadata
  test/gapic_config_service_v2_v2.ts
  test/gapic_logging_service_v2_v2.ts
  test/gapic_metrics_service_v2_v2.ts
Labels: api: logging, cla: yes

#954 ci: fix bucket_not_found race condition in log sink tests
  samples/test/sinks.test.js
  system-test/logging.ts
Labels: api: logging, cla: yes, priority: p2, type: process

#957 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#958 feat: add the Tailing API to get a live stream of the tail end of filtered logs
  protos/google/logging/v2/logging.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v2/logging_service_v2_client.ts
  src/v2/logging_service_v2_client_config.json
  synth.metadata
  test/gapic_logging_service_v2_v2.ts
Labels: api: logging, cla: yes, context: full
