Repository googleapis/nodejs-logging, pull requests merged in 2020-12, with the labels that each got.

#942 fix!: users can log httprequest logs without providing a log message
  src/log.ts
  system-test/logging.ts
  test/log.ts
Labels: api: logging, cla: yes, priority: p2

#955 perf!: getEntries filters 24 hour timestamp by default
  src/index.ts
  test/index.ts
Labels: api: logging, cla: yes, priority: p2

#962 fix: only apply logName to filter when not already present
  src/log.ts
  test/log.ts
Labels: api: logging, cla: yes

#966 chore: generate GAPIC metadata JSON file
  src/v2/gapic_metadata.json
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#968 test: reenable multiple entry test with null payload value
  system-test/logging.ts
Labels: api: logging, cla: yes, priority: p2

#974 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#978 ci: fix bucket_not_found for samples tests
  samples/test/sinks.test.js
Labels: api: logging, cla: yes, priority: p2, type: bug
