Repository googleapis/nodejs-logging, pull requests merged in 2020-08, with the labels that each got.

#863 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#864 fix(docs): jsdoc strings were malformed
  src/index.ts
Labels: cla: yes

#869 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#872 fix: make request batching work again
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  src/v2/config_service_v2_client.ts
  src/v2/logging_service_v2_client.ts
  src/v2/metrics_service_v2_client.ts
  synth.metadata
Labels: cla: yes

#874 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#878 chore: Add Observability DevX team to logging lib owners
  .github/CODEOWNERS
Labels: cla: yes

#879 fix(deps): require google-gax 2.7.0
  package.json
Labels: api: logging, cla: yes, kokoro:run

#884 build: track flaky tests for "nightly", add new secrets for tagging
  .github/publish.yml
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full
