Repository googleapis/nodejs-logging, pull requests merged in 2020-07, with the labels that each got.

#844 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#845 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#846 chore: change retry code names from autosynth
  protos/google/logging/v2/log_entry.proto
  protos/google/logging/v2/logging.proto
  protos/google/logging/v2/logging_config.proto
  protos/google/logging/v2/logging_metrics.proto
  src/v2/config_service_v2_client.ts
  src/v2/config_service_v2_client_config.json
  src/v2/logging_service_v2_client.ts
  src/v2/logging_service_v2_client_config.json
  src/v2/metrics_service_v2_client_config.json
  synth.metadata
Labels: cla: yes, context: none

#850 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#848 build: address typo in gitattributes
  .gitattributes
  synth.metadata
Labels: cla: yes, context: partial, gitattribute.*, in

#851 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#855 build: fix typo in publish
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#856 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#857 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#858 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#860 chore: delete Node 8 templates, move gitattribute files to node templates
  .gitattributes
  .kokoro/continuous/node8/common.cfg
  .kokoro/continuous/node8/test.cfg
  synth.metadata
Labels: cla: yes, context: full

#861 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#862 build: protos update
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: none
