Repository googleapis/nodejs-logging, pull requests merged in 2020-06, with the labels that each got.

#825 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v2/config_service_v2_client.ts
  src/v2/logging_service_v2_client.ts
  src/v2/metrics_service_v2_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#827 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#828 fix(sample-test): we shouldn't delete node_modules after link
  package.json
Labels: cla: yes

#832 fix: handle fallback option properly
  protos/google/logging/v2/log_entry.proto
  protos/google/logging/v2/logging.proto
  protos/google/logging/v2/logging_config.proto
  protos/google/logging/v2/logging_metrics.proto
  protos/protos.json
  src/v2/config_service_v2_client.ts
  src/v2/logging_service_v2_client.ts
  src/v2/metrics_service_v2_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#834 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#839 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
