Repository googleapis/nodejs-logging, pull requests merged in 2020-05, with the labels that each got.

#806 feat: add Blunderbuss config
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#809 fix: linting and formatting
  synth.metadata
  test/gapic_config_service_v2_v2.ts
  test/gapic_logging_service_v2_v2.ts
  test/gapic_metrics_service_v2_v2.ts
  test/index.ts
Labels: automerge, cla: yes

#810 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#817 test: skip failing test until we can dig into the issue
  system-test/logging.ts
Labels: cla: yes
