Repository googleapis/nodejs-logging, pull requests merged in 2020-03, with the labels that each got.

#731 build(test): adds support for build cop, fixes codecov.io
  .github/workflows/ci.yaml
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .mocharc.js
  .mocharc.json
Labels: cla: yes

#732 chore: test build cop
  samples/test/quickstart.test.js
  system-test/logging.ts
  test/log.ts
Labels: cla: yes

#734 build: mocharc needs to export
  .mocharc.js
Labels: cla: yes

#738 test: remove fake failing tests used to test build-cop
  samples/test/quickstart.test.js
  system-test/logging.ts
  test/log.ts
Labels: cla: yes

#733 build: update linkinator config
  linkinator.config.json
Labels: automerge, cla: yes

#721 chore(test): Ensure writeLogEntries is actually called on log write.
  src/log.ts
  test/log.ts
Labels: cla: yes

#725 fix(docs): documentation for overloaded methods
  src/index.ts
  src/log.ts
  src/sink.ts
Labels: automerge, cla: yes, kokoro:force-run

#744 chore: update uuid dependency
  package.json
  system-test/logging.ts
Labels: cla: yes

#740 fix!: proto annotations
  protos/google/logging/v2/log_entry.proto
  protos/google/logging/v2/logging.proto
  protos/google/logging/v2/logging_config.proto
  protos/google/logging/v2/logging_metrics.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v2/config_service_v2_client.js
  src/v2/config_service_v2_client_config.json
  src/v2/doc/google/api/doc_monitored_resource.js
  src/v2/doc/google/logging/v2/doc_log_entry.js
  src/v2/doc/google/logging/v2/doc_logging.js
  src/v2/doc/google/logging/v2/doc_logging_config.js
  src/v2/doc/google/logging/v2/doc_logging_metrics.js
  src/v2/logging_service_v2_client.js
  src/v2/logging_service_v2_client_config.json
  src/v2/metrics_service_v2_client.js
  src/v2/metrics_service_v2_client_config.json
  synth.metadata
  test/gapic-v2.js
Labels: cla: yes

#751 chore: remove snippet leading whitespace
  README.md
Labels: automerge, cla: yes

#754 test: allow appropriate waiting times
  system-test/logging.ts
Labels: cla: yes

#755 docs: demonstrate how to set log level
  samples/quickstart.js
Labels: cla: yes

#762 docs: document version support goals
  README.md
Labels: automerge, cla: yes
