Repository googleapis/nodejs-logging, pull requests merged in 2020-02, with the labels that each got.

#696 chore: skip img.shields.io in docs test
  linkinator.config.json
Labels: cla: yes

#698 test: make less requests to avoid quota limit
  system-test/logging.ts
Labels: cla: yes, do not merge

#695 test: modernize mocha config
  .mocharc.json
  package.json
  test/mocha.opts
Labels: cla: yes

#699 test: retry rate limit deletion errors
  system-test/logging.ts
Labels: cla: yes

#700 feat: add CMEK config and update grpc config logic
  protos/google/logging/v2/log_entry.proto
  protos/google/logging/v2/logging.proto
  protos/google/logging/v2/logging_config.proto
  protos/google/logging/v2/logging_metrics.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v2/config_service_v2_client.js
  src/v2/config_service_v2_client_config.json
  src/v2/doc/google/logging/v2/doc_log_entry.js
  src/v2/doc/google/logging/v2/doc_logging.js
  src/v2/doc/google/logging/v2/doc_logging_config.js
  src/v2/doc/google/logging/v2/doc_logging_metrics.js
  src/v2/logging_service_v2_client.js
  src/v2/metrics_service_v2_client.js
  synth.metadata
  test/gapic-v2.js
Labels: cla: yes

#703 test: ignore getLogs() error in cleanup
  system-test/logging.ts
Labels: cla: yes

#707 build: add GitHub actions config for unit tests
  .github/workflows/ci.yaml
  package.json
Labels: cla: yes

#706 test: grant proper permissions to bucket destination
  system-test/logging.ts
Labels: cla: yes

#704 fix: use logging api resource for metric
  protos/google/logging/v2/logging.proto
  protos/google/logging/v2/logging_metrics.proto
  protos/protos.json
  synth.metadata
Labels: cla: yes

#693 docs(samples): move awaits into async scope
  samples/http-request.js
  samples/logs.js
  samples/quickstart.js
  samples/sinks.js
Labels: cla: yes

#712 fix(types): write options dryRun and partialSuccess (#711)
  src/log.ts
  test/log.ts
Labels: cla: yes

#713 fix(docs): orderBy sample and documentation
  samples/logs.js
  src/index.ts
Labels: cla: yes

#708 fix(docs): writeLog should be in async function
  README.md
  synth.metadata
Labels: automerge, cla: yes

#724 chore(docs): stackdriver logging limits of 256kb/entry and 10mb/write…
  package.json
  src/entry.ts
  src/index.ts
  src/log.ts
Labels: cla: yes

#726 feat: export protos in src/index.ts
  src/index.ts
Labels: automerge, cla: yes

#728 build: add publish.yml enabling GitHub app for publishes
  .github/publish.yml
Labels: automerge, cla: yes

#729 chore: update jsdoc.js
  .jsdoc.js
Labels: automerge, cla: yes
