Repository googleapis/nodejs-logging, pull requests merged in 2021-12, with the labels that each got.

#1187 fix 186981671: The use of "synchronously" is a bit wrong on the help page
  samples/logs.js
Labels: cla: yes, priority: p2, api: logging, samples

#1189 fix: Correct a comment in sample regarding asynchronous log writing
  samples/logs.js
Labels: cla: yes, api: logging, samples

#1191 chore: add additional option to populate http request metadata
  .readme-partials.yml
  README.md
Labels: api: logging

#1194 fix: update links for TSDoc
  src/entry.ts
  src/index.ts
  src/log-sync.ts
  src/log.ts
  src/sink.ts
Labels: api: logging

#1197 fix: update links for TSDoc
  src/entry.ts
Labels: api: logging

#1199 chore: move nested sample
  samples/http-request.js
Labels: automerge, api: logging, samples

#1177 fix: Setting maxEntrySize does not truncate big json payloads correctly
  src/log.ts
  test/entry.ts
  test/index.ts
  test/log.ts
Labels: cla: yes, api: logging

#1202 Enable staleness and pull request size bots on repository
  .github/auto-label.yaml
Labels: api: logging
