Repository googleapis/nodejs-logging, pull requests merged in 2021-06, with the labels that each got.

#1086 feat: users can log raw http request objects with trace
  src/entry.ts
  src/log.ts
  src/make-http-request.ts
  src/middleware/express/make-http-request.ts
  src/middleware/express/make-middleware.ts
  system-test/logging.ts
  test/entry.ts
  test/log.ts
  test/middleware/express/test-make-http-request.ts
  test/test-make-http-request.ts
Labels: api: logging, cla: yes, priority: p2, type: feature request

#1088 feat: detect Google and W3C trace context (including in middleware)
  package.json
  src/context.ts
  src/entry.ts
  src/http-request.ts
  src/log.ts
  src/make-http-request.ts
  src/middleware/context.ts
  src/middleware/express/make-middleware.ts
  system-test/logging.ts
  test/context.ts
  test/entry.ts
  test/http-request.ts
  test/log.ts
  test/middleware/express/test-make-middleware.ts
  test/middleware/test-context.ts
  test/test-make-http-request.ts
Labels: api: logging, cla: yes, priority: p2, type: feature request

#1100 fix: allow unformatted originalURL input
  src/http-request.ts
  test/http-request.ts
Labels: api: logging, automerge, cla: yes

#1108 chore: update blunderbuss.yml
  .github/blunderbuss.yml
Labels: api: logging, cla: yes

#1111 fix(deps): google-gax v2.17.0 with mTLS
  package.json
Labels: api: logging, cla: yes
