Repository googleapis/nodejs-logging, pull requests merged in 2021-05, with the labels that each got.

#1061 fix(deps): require google-gax v2.12.0
  package.json
Labels: api: logging, automerge, cla: yes

#1063 build: release minified package under new name
  .kokoro/publish-min.sh
  .readme-partials.yml
  README.md
  owlbot.py
  package.json
  samples/README.md
Labels: api: logging, cla: yes, priority: p2

#1071 chore: fix endless publishing loop
  .kokoro/publish-min.sh
Labels: api: logging, cla: yes

#1074 test: add required gcloud components
  .kokoro/environment.sh
Labels: api: logging, cla: yes

#1077 fix: Object implementing toString not logged as Object
  src/common.ts
  src/entry.ts
Labels: api: logging, cla: yes, priority: p1, type: bug
