Repository googleapis/nodejs-logging, pull requests merged in 2021-01, with the labels that each got.

#979 fix: synth.py pipeline
  synth.py
Labels: api: logging, cla: yes

#981 chore: update dates
  .jsdoc.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v2/config_service_v2_client.ts
  src/v2/index.ts
  src/v2/logging_service_v2_client.ts
  src/v2/metrics_service_v2_client.ts
  synth.metadata
  system-test/install.ts
  test/gapic_config_service_v2_v2.ts
  test/gapic_logging_service_v2_v2.ts
  test/gapic_metrics_service_v2_v2.ts
Labels: api: logging, automerge, cla: yes, context: none

#983 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full
