Repository googleapis/nodejs-logging, pull requests merged in 2021-04, with the labels that each got.

#1020 fix(deps): drop dependency on type-fest
  package.json
  src/entry.ts
Labels: api: logging, cla: yes, priority: p2, type: process

#1021 fix(deps): drop dependency on is
  .gitignore
  package.json
  src/common.ts
  src/entry.ts
Labels: api: logging, cla: yes, priority: p2, type: cleanup

#1030 chore: update blunderbuss to auto assign nicole
  .github/blunderbuss.yml
Labels: api: logging, cla: yes

#1028 fix: cloud functions resource.labels.region undefined
  src/metadata.ts
  test/metadata.ts
Labels: api: logging, cla: yes

#1023 fix(deps): remove dependency on through2
  package.json
  src/index.ts
  test/index.ts
Labels: api: logging, cla: yes, priority: p2, type: enhancement

#1034 fix: accept uniqueWriterIdentity in setMetadata
  src/index.ts
  src/sink.ts
  system-test/logging.ts
Labels: api: logging, automerge, cla: yes, priority: p1, type: bug

#1038 chore(deps): remove snakecase-keys dependency
  package.json
  src/log.ts
  test/log.ts
Labels: api: logging, automerge, cla: yes

#1048 chore(deps): remove dev dependency @types/tmp
  package.json
Labels: api: logging, cla: yes

#1049 chore(deps): remove explicit dev dependency execa
  package.json
Labels: api: logging, cla: yes

#1050 chore(deps): remove dev dependencies mv and ncp
  package.json
Labels: api: logging, cla: yes
