Repository googleapis/nodejs-logging, pull requests merged in 2021-03, with the labels that each got.

#998 feat: tail entries wrapper
  src/index.ts
  src/log.ts
  system-test/logging.ts
  test/log.ts
Labels: api: logging, cla: yes, priority: p2, type: feature request

#1001 build: update gapic-generator-typescript to v1.2.10.
  synth.metadata
  webpack.config.js
Labels: api: logging, automerge, cla: yes, context: full

#1002 build: updates to generated protos
  protos/protos.json
  synth.metadata
Labels: api: logging, cla: yes, context: none

#1005 test: environment test for Cloud Functions
  .kokoro/environment.sh
  .kokoro/environment/common.cfg
  .kokoro/environment/functions.cfg
  .trampolinerc
  synth.py
Labels: api: logging, cla: yes, priority: p2

#1007 [CHANGE ME] Re-generated to pick up changes from self.
  .trampolinerc
  synth.metadata
Labels: api: logging, cla: yes, context: none

#1009 docs: add tailEntries sample and docs
  .eslintignore
  samples/logs.js
  src/index.ts
  synth.py
Labels: api: logging, cla: yes, priority: p2, samples

#1012 chore: add in updated compiled protos
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
Labels: api: logging, cla: yes, priority: p2

#1011 docs: update doc properties for GetLogsResponse and GetEntriesResponse
  src/index.ts
Labels: api: logging, cla: yes

#1014 test: fix environment test script
  .eslintignore
  .kokoro/environment.sh
  .prettierignore
  synth.py
Labels: api: logging, cla: yes
