Repository googleapis/nodejs-logging, pull requests merged in 2021-02, with the labels that each got.

#985 chore: update common proto files
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: logging, cla: yes, context: none

#987 chore: use repo metadata to populate nodejs CODEOWNERS
  .github/CODEOWNERS
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#986 docs: improve write structured logEntry example
  samples/logs.js
Labels: api: logging, cla: yes, priority: p2
