Repository googleapis/nodejs-logging, pull requests merged in 2022-07, with the labels that each got.

#1306 fix: Change image in readme to a static link
  .readme-partials.yml
  README.md
  samples/README.md
Labels: automerge, api: logging, size: xs

#1305 fix: Logging to stdout in Cloud Run creates a JSON object as "message"
  src/entry.ts
  src/log-sync.ts
  test/entry.ts
Labels: api: logging, size: m

#1307 fix: Add LogSyncOptions parameter to Logging.logSync() API
  src/index.ts
  test/index.ts
Labels: api: logging, size: s
