Repository googleapis/nodejs-logging, pull requests merged in 2022-09, with the labels that each got.

#1326 fix: maxRetries parameter is ignored
  src/log.ts
  test/log.ts
Labels: api: logging, size: s

#1328 fix: Correction for timestamp and instrumentation record severity fields format
  src/entry.ts
  src/utils/common.ts
  src/utils/instrumentation.ts
  test/entry.ts
Labels: api: logging, size: m

#1333 fix: google-gax resolution
  package.json
Labels: api: logging, size: xs
